### PR TITLE
Added transformation for TeX characters

### PR DESCRIPTION
**Pull request by khwolf**
---, --, \%, \&, and \_ are often used in my abstracts and even in titles.

### CODE REVIEW

**Comment by monperrus** [comment]
Hi, what's the difference between the two pull requests? They seem to have commits in common.
--Martin

**Comment by khwolf** [comment]
Hi, i made the mistake of building one on top of the other.
Basically the first commit (d3616b9) just adds some transformation (should be useful for every installation).
The second (3f86319) and third (a4693d3) commit add formating for vancouver style.
Thanks for considering the changes.
Klaus Hendrik

**Comment by khwolf** [comment]
Hi @monperrus,

do you want me to try to resubmit the two changes in two different pull request?
Do you consider them at all or just one of the two?

Best regards,

  Klaus Hendrik

**Comment by monperrus** [comment]
> do you want me to try to resubmit the two changes in two different
> pull request?
That would be great!

Best, --Martin

**Pull request closed without merging**
