### PR TITLE
USERS: add 1 indiv user + 1 group

### PR DESCRIPTION
**Pull request by sciunto**

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks, I'd be glad to merge it. Would you first remove the other spurious formatting changes?

**Comment by sciunto** [comment]
It's not spurious, it's cleaner :) No need to have trailing spaces.

**Comment by monperrus** [comment]
We need to have a clean and readable history.

**Comment by sciunto** [comment]
Ok, don't worry, no need to waste time for that.

**Pull request closed without merging**
