### PR TITLE
Make it compatible with https sites.

### PR DESCRIPTION
**Pull request by i2000s**
One issue with the current setting is that if one define `'BIBTEXBROWSER_LINKS_TARGET'` with `_self` or `_top` and use this plugin for a `https` site, the `doi` and `url` links may not work. This is because the `doi` other links were hard-coded with the `http` protocol by default and are incompatible with the `https` protocol of the host site server. I am making those change in this PR with tests in our website at https://cquic.unm.edu/cquic-publications/. I didn't use the default HTML wrapper in our site. Please review and test on your own if possible. Thank you for making this tool.

### CODE REVIEW

**Comment by monperrus** [comment]
what about using `//` directly as done on many sites today?

**Comment by i2000s** [comment]
That should also work. But I was forcing doi and google scholar to use `https` for a better security level regardless of the host. I think it doesn't hurt if the host uses `http` in that case. Feel free to use `//` though.

**Comment by i2000s** [comment]
In fact, if the doi/gsid uses `http` as the host does, it will be redirected to `https` on the browser. So, there will be a redirect to slow down the process in the end.

**Comment by monperrus** [comment]
Hi @i2000s One more question: why did you change the xmlns urls? simply a global search-and-replace or something else?

**Comment by i2000s** [comment]
@monperrus I thought the xmlns links would also generate some problems and all links were checked on my internet browser, but apparently, I was wrong when I read the standards documents recently. I just rolled back those xml links to the standard `http` protocol as documented on their standard examples. Please check if there is anything else I can do. Thanks.

**Comment by monperrus** [comment]
thanks a lot!

**Comment by fph** [comment]
Note that Crossref has [changed their guidelines](http://blog.crossref.org/2016/09/new-crossref-doi-display-guidelines.html) and now they recommend links in the format `https://doi.org/10.5240/B1FA-0EEC-C316-3316-3A73-L`: so with https and **without the dx. prefix**. You may want to drop the `dx.`, just to be compliant.

**Comment by i2000s** [comment]
@fph Please find the fix on PR #69. Thank you for pointing out this standard update!

**Pull request merged**
