### PR TITLE
Add composer.json for compatibility with composer

### PR DESCRIPTION
**Pull request by paxperscientiam**
Hi @monperrus ,

The composer.json file allows for the possibility of installing monperrus/bibtexbrowser with composer. Because it is not registered with packagist, I believe it is still necessary for composer users to include the following in their own project's composer.json:

``` json
"repositories": [
{
"type": "vcs",
            "url": "https://github.com/monperrus/bibtexbrowser.git"
        }
]
```

EDIT: grammar

### CODE REVIEW

**Comment by paxperscientiam** [comment]
Does not seem that autoloading is desirable, so I removed in from composer.json.

**Comment by paxperscientiam** [comment]
Before you accept this, let me tinker a bit.

**Comment by monperrus** [comment]
rebase to have a clean and short diff?

**Comment by paxperscientiam** [comment]
HI @monperrus , i will do that.

**Comment by paxperscientiam** [comment]
Submitting new PR

**Pull request closed without merging**
