### PR TITLE
WIP Added button for showing all entries (no search results) #109

### PR DESCRIPTION
**Pull request by LukasCBossert**
As discussed in #109

Note: The button has no function (yet) - because I have no idee how to fully implement that.

Thanks!

### CODE REVIEW

**Comment by monperrus** [comment]
Cool! The button has to a URL of the form `bibtexbrowser.php?bib=foo.bib&all`

**Comment by LukasCBossert** [comment]
ok, great. so, best if the bib-file is specified in the local.php ?!
Am 17. Mai 2020, 06:28 +0200 schrieb Martin Monperrus <notifications@github.com>:

**Comment by LukasCBossert** [comment]
> Cool! The button has to point to a URL of the form `bibtexbrowser.php?bib=foo.bib&all`

Well, I tried this but then it will open the result window in the small menue on the left - not what I imagined.

**Comment by monperrus** [comment]
would we finish this PR?

**Pull request closed without merging**
