### PR TITLE
render math in HTML vie MathJax

### PR DESCRIPTION
**Pull request by lpirl**
I added support for rendering math (`$…$`) via [MathJax](http://www.mathjax.org).
Therefore, the new configuration option `BIBTEXBROWSER_RENDER_MATH` as introduced.

### CODE REVIEW

**Comment by sciunto** [comment]
That's great. I'm a user and not a php dev, but I would suggest to have a way to change the CDN with an option. Some people may want to use their own mathjax instance for privacy for instance.

Thanks!

**Comment by lpirl** [comment]
True, there you go. 227df34

**Comment by monperrus** [comment]
Looks good, could you squash all the commits in a single one?

**Comment by lpirl** [comment]
Done.

**Comment by monperrus** [comment]
Merged. Thanks for PR. --Martin

**Pull request closed without merging**
