### PR TITLE
added support for Oxford commas in name lists

### PR DESCRIPTION
**Pull request by jenskober**
enables e.g. "Miroslaw Staron, Wilhelm Meding, and Christer Nilsson"  instead of "Miroslaw Staron, Wilhelm Meding and Christer Nilsson"

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot! Could you add a test case?

**Comment by jenskober** [comment]
Yes, I'll add a test case (hopefully tonight).
Would you like to keep this as option USE_OXFORD_COMMA or make that the default for LAST_AUTHOR_SEPARATOR?

**Comment by jenskober** [comment]
I now removed the option USE_OXFORD_COMMA and added a test. 

However, that would break, e.g., if somebody wants to always use ', ' as a separator. You either get
"Name1 Name2" "Name1, Name2, Name3" (LAST_AUTHOR_SEPARATOR = ' ') or
"Name1, Name2" "Name1, Name2, , Name3" (LAST_AUTHOR_SEPARATOR = ', ')

Thoughts?

**Comment by monperrus** [comment]
Thanks for the test!

> Would you like to keep this as option USE_OXFORD_COMMA

Yes to stay backward compatible. None of the existing asserts should change.

**Comment by monperrus** [comment]
Changed it a little bit. OK for you?

**Comment by jenskober** [comment]
should be backward compatible now

**Comment by monperrus** [comment]
Thanks a lot!

**Pull request merged**
