### PR TITLE
jquery uri in variable

### PR DESCRIPTION
**Pull request by sciunto**
Hi Martin,

To be consistent with MATHJAX, I defined a variable to customize jquery uri.

### CODE REVIEW

**Comment by monperrus** [comment]
the PR makes really sense, but is polluted by spurious formatting changes. Could you remove them? Thanks.

**Comment by sciunto** [comment]
@monperrus I just removed white spaces, which are not supposed to be there. You prefer two different commits?

**Comment by monperrus** [comment]
only one PR with the URL change, since bibtexbrowser does not use this
whitespace convention.

Thanks.

--Martin

**Comment by sciunto** [comment]
OK. I close this one to make a new one, to be clean.

**Pull request closed without merging**
