### PR TITLE
4 spaces

### PR DESCRIPTION
**Pull request by paxperscientiam**
Here are add an `editorconfig` file to help contributors adhere to two [PSR-2](https://www.php-fig.org/psr/psr-2/) style rules:
* "Code MUST use 4 spaces for indenting, not tabs."
* Also supposed to end with a newline

EDIT:

OK, the way I did this was no appropriate as I did not apply the new style to all of the files. I'll do that now and then you should review once that commit is pushed.

### CODE REVIEW

**Comment by paxperscientiam** [comment]
@monperrus OK, so this includes the editorconfig file and the test file and one of the wikis.

What do you think so far? Unfortunately, the diffing is annoying broken into large blocks...

**Comment by monperrus** [comment]
can we add a checkstyle for this property in the Travis CI?

**Comment by paxperscientiam** [comment]
@monperrus yes. sorry, forgot to reply

**Comment by monperrus** [comment]
I'm OK to change the formatting convention, but this has to be automatically checked in Travis.

**Comment by monperrus** [comment]
Thanks for the proposal.

**Pull request closed without merging**
