### PR TITLE
Refactor=1

### PR DESCRIPTION
**Pull request by paxperscientiam**
A bit of refactoring. The effort here is about separating logic from markup.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks. Since we don't have a super test suite. I'm hesitant to merge large refactoring, because even a careful code review can miss something. Would you be able to only put in the PR the separation refactoring (and not the other changes such as the introduction of `<<<CSS`)? Thanks!

**Comment by paxperscientiam** [comment]
Hello. Maybe I'm misunderstanding. `<<<CSS`, `<<<JS`, and `<<<HTML` are all the same in that they are merely identifiers for the heredocs; they don't affect interpretation by PHP.

I agree with you on the question of testing, which, admittedly, I know little about. Are the tests fed to travis not sufficient?

While we're on testing, I noticed that PHP4 is not included in the travis file. Are you dropping support for PHP4?

**Comment by monperrus** [comment]
> Are the tests fed to travis not sufficient?

no

> Are you dropping support for PHP4?

yes

**Comment by paxperscientiam** [comment]
OK, so made a PR updating the minimum PHP version. As for more comprehensive testing...IDK!

**Pull request closed without merging**
